#!/bin/bash

# dmenu command
dmenu='dmenu -i -p System -h 23 -nb #E9E9E9 -nf #000000 -sb #E9E9E9 -sf #2575EE -fn Convergence-14:normal'
# time before auto-halt

wait_time=60s

cmd=$(echo -e "lock\nlog-out\nshutdown\nreboot\nsuspend" | $dmenu)

sleep_action(){
  sleep ${wait_time}
  case $1 in
    shutdown)
      systemctl poweroff
      ;;
    reboot)
       systemctl reboot
       ;;
    esac
}

case $cmd in
  shutdown)
    # shutdown if no intervention
    sleep_action $cmd &
    # set pid of command
    sleep_pid="$!"

    # ask to confirm shutdown
    zenity --question --text "Do you really want to shutdown?"
    [ $? = 0 ] && systemctl poweroff || kill ${sleep_pid}
    ;;
  reboot)
    # Reboot if no intervention
    sleep_action $cmd &
    # Set pid of command
    sleep_pid="$!"

    # Ask to confirm reboot
    zenity --question --text "Do you really want to reboot?"
    [ $? = 0 ] && systemctl reboot || kill ${sleep_pid}
    ;;
  suspend)
    # Lock screen
    /home/$USER/bin/lockscreen
    # Suspend
    systemctl suspend
    ;;
  lock)
    /home/$USER/bin/lockscreen
    ;;
  log-out)
    i3-msg exit
    ;;
esac
