#!/bin/bash

# You can call this script like this:
# $./volume.sh up
# $./volume.sh down
# $./volume.sh mute

function get_volume {
    amixer get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1
}

function is_mute {
    amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function send_notification {
    volume=`get_volume`
	icon="high";
	if [ $volume -lt 66 ]; then
		icon="medium";
	fi
	if [ $volume -lt 33 ]; then
		icon="low";
	fi
	if [ $volume -eq 0 ]; then
		icon="off";
	fi
    # Make the bar with the special character ─ (it's not dash -)
    # https://en.wikipedia.org/wiki/Box-drawing_character
	bar=$(seq -s "█" $((1+$volume / 5)) | sed 's/[0-9]//g')$(seq -s "─" $((1+(100-$volume)/5))| sed 's/[0-9]//g')
    # Send the notification
    dunstify -u low -i notification-audio-volume-$icon -r 2593 "$bar"
}

case $1 in
    up)
	# Set the volume on (if it was muted)
	amixer -D pulse set Master on > /dev/null
	# Up the volume (+ 5%)
	amixer -D pulse sset Master 5%+ > /dev/null
	send_notification
	;;
    down)
	amixer -D pulse set Master on > /dev/null
	amixer -D pulse sset Master 5%- > /dev/null
	send_notification
	;;
    mute)
    	# Toggle mute
	amixer -D pulse set Master 1+ toggle > /dev/null
	if is_mute ; then
	    dunstify -u low -i notification-audio-volume-muted -r 2593 "Mute"
	else
	    send_notification
	fi
	;;
esac

# update i3bar
pkill -RTMIN+1 i3blocks
